### ISSUE TITLE
Keyboard layout etc. should follow language selection

### ISSUE THREAD

**Issue by scootergrisen** [ghostbsd/gbi#16]
When i select language like "Danish" i would like for danish keyboard layout to be selected by default and also europe/copenhagen.

I'm guessing that if you select a specific language that most times the user would also like to use that keyboard layout and the timezone that might be for that language so its easier to go though the installer.

Not sure if i should write this only here or also in https://github.com/ghostbsd/gbinstall

**Comment by vimanuelt** [comment]
After much thought, implementing this idea is not a good idea. Language selection cannot determine keyboard layout and timezone in majority of use cases. This is too limited a use case.
