### ISSUE TITLE
Unable to install on device with Windows already installed

### ISSUE THREAD

**Issue by Qiangong2** [ghostbsd/gbi#20]
We have tried to troubleshoot this in telegram quite a bit.

I have 8 different partitions on my hard drive. Partitions 1-4 and 8 are in use by windows. 5,6 and 7 are available to be used by GhostBSD. When I try and install using the auto button on custom configuration, it fails, saying it cannot read the partition. However, it will delete and create the partitions on the hard disk, but install the files to the bootable usb.

Here is my pcinstall.cfg: https://paste.ubuntu.com/p/DWfrtzhCZ4/
My `sudo gbi` output: https://paste.ubuntu.com/p/4MYSmpdfJj/  (It starts installing to the usb, so I stopped it).
pc-sysinstall.log: https://paste.ubuntu.com/p/Z4ZPq5xHdn/

**Comment by ericbsd** [comment]
https://github.com/ghostbsd/gbi/commit/a0f8ec98562741c3ca5b3534cb6668e36a1fe6df

**Comment by ericbsd** [comment]
the new dev ISO here https://download.ghostbsd.org/development/amd64/latest/ should fix the problem on the log including the wrong partition mounting on installation.

**Comment by ericbsd** [comment]
https://github.com/ghostbsd/gbi/issues/29
