### ISSUE TITLE
Logs should persist until the live system is shut down (just like pc-sysinstall's)

### ISSUE THREAD

**Issue by allentiak** [ghostbsd/gbi#26]
Currently, they are deleted once the graphical installation finishes.

**Comment by allentiak** [comment]
This will help debugging the installer.

**Comment by vimanuelt** [comment]
Duplicate ticket.

**Comment by allentiak** [comment]
@vimanuelt 
Great that someone reported this before me!
Could you please point me to the original of this ticket? I opened this one because I couldn't find it...
