### ISSUE TITLE
gbi cannot reuse already existent ZFS partitions

### ISSUE THREAD

**Issue by allentiak** [ghostbsd/gbi#27]
If I run the installer on a system which already has GhostBSD installed, it does not offer the option to reuse those partitons (nor to overwrite them). The only option is to delete them and to create them again afterwards.

**Comment by vimanuelt** [comment]
Duplicate ticket.

**Comment by allentiak** [comment]
@vimanuelt 
Great that someone reported this before me!
Could you please point me to the original of this ticket? I opened this one because I couldn't find it...
