### ISSUE TITLE
Dependencies?

### ISSUE THREAD

**Issue by prp-e** [ghostbsd/gbi#30]
I just installed `gbi` on a FreeBSD machine to test. I got some errors while partitioning (no surprise, because `gbi` wasn't really running from CD, it was from the HDD). Is there any dependencies besides `pc-sysinstall` ?

**Comment by ericbsd** [comment]
pygobject, ghostbsd/pc-sysinstall and sudo it should run even if on a drive, but it is not tested on FreeBSD so I am not sure it is working on FreeBSD.
