### ISSUE TITLE
Remove slide from the gpi install.py

### ISSUE THREAD

**Issue by probonopd** [ghostbsd/gbi#37]
The Live ISO contains 86.6 MB worth of gbi `slide-images`. Are those really needed? I think the objective for the artwork of the installer would be significantly under 1 MB, especially on Live ISOs, where every byte gets copied into precious RAM at boot time...

**Comment by probonopd** [comment]
Things like this would help for https://github.com/ghostbsd/ghostbsd-build/issues/110.

**Comment by vimanuelt** [comment]
I think you would be better served to use furybsd-livecd as it is based on FreeBSD.

**Comment by ericbsd** [comment]
@probonopd Your welcome to fork and make it your own, it is BSD licensed after all. The scope of GhostBSD is not to be lightweight. Just to clarify the actual GBI as an installer will be deprecated. GBI is going under major chages which will make it a set of reusable interface for mutiple project like installer, post installation, wecome app and more projects.

**Comment by ericbsd** [comment]
I changed my mind about this ticket.

The slide will be replaced with an animated gif.
