### ISSUE TITLE
When using GBI with GhostBSD KDE

### ISSUE THREAD

**Issue by ericbsd** [GhostBSD/gbi#5]
hostbsd@ghostbsd:~ % sudo gbi
No protocol specified
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
Unable to init server: Could not connect to 127.0.0.1: Connection refused
No protocol specified
Unable to init server: Could not connect to 127.0.0.1:  �
/usr/local/lib/gbi/slides.py:20: Warning: g_object_get_qdata: assertion 'G_IS_OBJECT (object)' failed
  styleContext = Gtk.StyleContext()
Segmentation fault
ghostbsd@ghostbsd:~ % sudo gbi

**Comment by angelescuo** [comment]
Hi,
It seems that you managed to start kde.
indeed using sudo gbi I have those messages.
It seems that in gnome, mate, xfce a polkit rule is used and is not installed in kde.
If we don't want to rely on any polkit rule for gbi we need to change install.py to be able to:
umount media/GhostBSD using sudo
stop and start hald using sudo
launch pc-sysinstall using sudo
and shutdown -r using sudo.
If we'll do that gbi won't depend of any polkit rule.
